import { useEffect, useReducer } from "react";
import { WELCOME_PAGE_SLUG } from "./canvasUrl";

// Auto-discovers the boards dropped under <canvases dir>/<slug>/*.html, one folder per board
// (a cloned app, a feature round, a design-system sheet). Each folder becomes a tldraw page; each
// HTML file in it becomes one shape. Add or edit files there; nothing here needs to change.
//
// The three maps come from a module generated by the `prototyping-canvases` plugin in
// vite.config.ts, which reads PROTOTYPING_CANVASES_DIR and falls back to this repo's own
// mockups/canvases. They were `import.meta.glob` calls until the canvas app started shipping
// inside an installable plugin: a glob pattern is a string literal resolved at build time, so it
// could only ever read one hard-coded directory, never the boards of whoever installed it.
//
// `fileLoaders` stays lazy — one chunk per file, fetched the first time a shape asks for it, so
// opening the welcome page pulls a dozen covers rather than every board (the full set is 25 MB of
// HTML, which a phone should not download to look at one page). Vite still reloads the page when a
// mockup is saved. `rawLayouts` and `rawIcons` stay eager because they are read during render.
import { boardPages, fileLoaders, rawLayouts, rawIcons, rawAssetNames } from "virtual:canvases";

export interface CanvasLibraryFile {
  path: string;
  pageSlug: string;
  pageName: string;
  fileName: string;
  title: string;
}

/**
 * How far along a board is. `live` is the default, the version being shipped, and it is the
 * one status that draws no tab on the canvas: most boards on a finished page
 * are live, and a tab on every one of them would say nothing while costing 134px of every
 * row. The other two draw a coloured tab above the board.
 *
 * It is a tldraw shape the layout places, not markup in the board, so a board keeps no record
 * of its own status and survives being regenerated when that status changes.
 */
export type CanvasBoardStatus = "exploring" | "outdated" | "live";

/** The default: what a board is when neither its entry nor its folder says otherwise. */
export const DEFAULT_BOARD_STATUS: CanvasBoardStatus = "live";

/** Title Case for the badge and the menu, per Geist's own Badge copy rule. */
export const BOARD_STATUS_LABEL: Record<CanvasBoardStatus, string> = {
  exploring: "Exploring",
  outdated: "Outdated",
  live: "Live",
};

/** In menu order: what you are exploring, what it replaced, what shipped. */
export const BOARD_STATUSES = Object.keys(
  BOARD_STATUS_LABEL,
) as CanvasBoardStatus[];

/**
 * A row's file, either by name alone (uses that file's humanized title) or with a label
 * override. `w`/`h` override the 478 x 980 artboard for a board that is not phone-shaped,
 * a landscape banner say; a row is laid out at its first file's size, so give every file
 * in the row the same one.
 *
 * `status` overrides the folder's own `status` for this one board, including back to
 * `live` to drop a tab the folder would otherwise give it.
 */
export type CanvasLayoutFileEntry =
  | string
  | {
      file: string;
      label?: string;
      w?: number;
      h?: number;
      status?: CanvasBoardStatus;
    };

/** A button under a row that opens an address in a new tab. */
export interface CanvasLayoutLink {
  label: string;
  url: string;
}

export interface CanvasLayoutRow {
  title: string;
  files: CanvasLayoutFileEntry[];
  /** Prefix each caption with its 1-based position in `files`, e.g. "3 · Referral". */
  numbered?: boolean;
  /**
   * Buttons under this row's boards. Boards render in `<iframe srcDoc sandbox="">`, where a
   * link cannot navigate anything, so anything clickable has to be a shape out here.
   */
  links?: CanvasLayoutLink[];
}

export interface CanvasLayoutConfig {
  /**
   * Page name override. Without one the folder slug is humanized, which cannot
   * express casing or punctuation: "notion-ios" becomes "Notion Ios", never
   * "(example) Notion iOS". Set this when the humanized name reads wrong. Every
   * folder shipped with the repo is an example, and says so as a "(example) "
   * prefix, so a board of your own stands out from them in the page menu.
   */
  name?: string;
  /**
   * Board that stands in for this folder on the welcome page, by file name,
   * e.g. "00-launch-light". Without one the cover is the folder's first board
   * that is not a 00- sheet, which is a token board on most of them.
   */
  cover?: string;
  /**
   * Where the folder sits in the page menu and the welcome row: lower first, default 0,
   * ties keep slug order. The welcome page stays on top whatever anyone declares.
   */
  order?: number;
  /**
   * The part of the cover board a welcome card shows, `[x, y, w, h]` in board px.
   * Default is the phone frame every folder here draws at the same place, so cards
   * crop to the mockup instead of framing it in artboard margin. Declare one for a
   * board that is not a phone, e.g. a full-bleed sheet: `[0, 0, 478, 980]`.
   */
  coverBox?: [number, number, number, number];
  /**
   * The status every board in this folder has unless its own entry says otherwise: the
   * useful default on a folder that is one round of exploration, where saying it 70 times
   * would be 70 chances to leave one board saying something else.
   */
  status?: CanvasBoardStatus;
  rows: CanvasLayoutRow[];
}

/**
 * The artboard a board is drawn at unless its layout entry says otherwise. Matches the v1.14+
 * phone mockups' own canvas: .phone{430x932} + body{padding:24px}. Here rather than with the
 * shape that draws it, because the sheet page needs the size too and must not import tldraw to
 * read one pair of numbers.
 */
export const CANVAS_FILE_DEFAULT_SIZE = { w: 478, h: 980 } as const;

export function humanize(slug: string) {
  return slug
    .replace(/[-_]+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const FILE_PATTERN = /canvases\/([^/]+)\/([^/]+)\.html$/;

/** The tldraw page name for a folder: its layout.json `name`, else the humanized slug. */
export function pageNameFor(pageSlug: string) {
  return readCanvasLayout(pageSlug)?.name ?? humanize(pageSlug);
}

function parse(path: string): CanvasLibraryFile | null {
  const match = FILE_PATTERN.exec(path);
  if (!match) return null;
  const [, pageSlug, fileName] = match;
  return {
    path,
    pageSlug,
    pageName: pageNameFor(pageSlug),
    fileName,
    title: humanize(fileName),
  };
}

/**
 * A board's status: its own entry's in layout.json, else its folder's, else `live`. Read from
 * the layout by file name the same way the artboard size override is, so the board itself
 * carries no record of it.
 */
export function boardStatusForPath(path: string): CanvasBoardStatus {
  const file = parse(path);
  if (!file) return DEFAULT_BOARD_STATUS;
  const layout = readCanvasLayout(file.pageSlug);
  let status = layout?.status;
  for (const row of layout?.rows ?? []) {
    for (const entry of row.files) {
      if (typeof entry === "string" || entry.file !== file.fileName) continue;
      if (entry.status) status = entry.status;
    }
  }
  return status ?? DEFAULT_BOARD_STATUS;
}

/**
 * The status a tab is drawn for, or undefined for the ones that draw none. `live` is the
 * default and the majority, so it draws nothing on the canvas and shows only in the inspector,
 * where there is one board on screen and the badge is also the control that changes it.
 */
export function boardTabStatusForPath(path: string) {
  const status = boardStatusForPath(path);
  return status === DEFAULT_BOARD_STATUS ? undefined : status;
}

/**
 * Writes a board's status into its folder's layout.json, through the dev server (vite.config.ts).
 * The server edits the one entry as text rather than reparsing the file, so hand formatting and
 * key order survive; it then sends the edited layout back over HMR (`sp:board-status`, below), and
 * the canvas repaints without a reload.
 *
 * Only the dev server can write. A built canvas is static files on a host with no repo behind
 * them, which is why the badge is not a button there.
 */
export async function writeBoardStatus(path: string, status: CanvasBoardStatus) {
  const file = parse(path);
  if (!file) return false;
  const response = await fetch("/__sp/board-status", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ slug: file.pageSlug, file: file.fileName, status }),
  });
  return response.ok;
}

/**
 * Copies a canvas folder under a new name, through the dev server (vite.config.ts), and answers
 * the slug it ended up with. The typed name is what the page is called, the slug is what the
 * folder is called, and only the server knows the second one is free.
 *
 * Dev server only, like writeBoardStatus and for the same reason.
 */
export async function cloneCanvas(slug: string, name: string) {
  const response = await fetch("/__sp/clone-canvas", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ slug, name }),
  });
  const body = await response.text();
  if (!response.ok) throw new Error(body);
  return JSON.parse(body).slug as string;
}

/**
 * Appended to every board. A wheel event whose target is inside an iframe never reaches the
 * parent document, so tldraw's own fix for this — preventDefault on the wheel that reaches its
 * container, in useGestureEvents — never runs, and the browser turns the horizontal part of a
 * two-finger pan into a back navigation. The page's own `overscroll-behavior: none` in index.css
 * cannot reach in: overscroll chains one frame at a time, so a board has to stop the chain in its
 * own document. Every iframe in this app gets one, because the ones that can be panned over are
 * not the same set in every browser and the fix has already been missed once per site.
 *
 * Appended rather than spliced: 37 of the repo's 180 boards emit no `</body>`, and a tag put
 * before the doctype would drop the board into quirks mode. A trailing `<style>` is parsed into
 * the body, and the inspector agent skips STYLE elements, so this adds no layer.
 */
const NO_OVERSCROLL = "<style>html{overscroll-behavior:none}</style>";

/** path -> the HTML every board iframe renders, for every file fetched so far. */
export const canvasFileHtml = new Map<string, string>();
const canvasFileLoads = new Map<string, Promise<string | undefined>>();

/** Whether a discovered board exists at this path, loaded or not. */
export function hasCanvasFile(path: string) {
  return path in fileLoaders;
}

/** Fetches a board's HTML once and caches it; resolves undefined for a path that is not a board. */
export function loadCanvasFileHtml(path: string): Promise<string | undefined> {
  const cached = canvasFileHtml.get(path);
  if (cached !== undefined) return Promise.resolve(cached);
  const loader = fileLoaders[path];
  if (!loader) return Promise.resolve(undefined);
  let load = canvasFileLoads.get(path);
  if (!load) {
    load = loader()
      .then((html) => {
        const board = html + NO_OVERSCROLL;
        canvasFileHtml.set(path, board);
        return board;
      })
      // A chunk can fail to arrive — a board deleted between discovery and first render, a
      // dev-server restart mid-flight. Without this the rejected promise stays in the map and
      // the shape is blank for good, because every later call hands back the same rejection.
      .catch(() => undefined)
      .finally(() => {
        canvasFileLoads.delete(path);
      });
    canvasFileLoads.set(path, load);
  }
  return load;
}

/**
 * Where a board is a web page of its own, for the buttons that open one, and undefined for a
 * path that is not a board. `/board/<slug>/<file>.html`: the dev server reads it off the boards
 * directory, a build emits it as a file (see the `prototyping-canvases` plugin).
 *
 * An address rather than the `blob:` URL this was at first. A blob has no address to link, copy
 * or reload, and it is a page the browser calls restricted, which is enough for an extension —
 * a Figma importer, a reader, a screenshotter — to refuse to work on it at all.
 */
export function boardPageUrl(path: string): string | undefined {
  return boardPages[path];
}

/**
 * A rendering shape's board HTML: undefined until its chunk arrives, then the string. Every shape
 * on the page mounts (culling only hides the off-screen ones), so a page fetches its own boards
 * and nothing else. The cache is the source of truth and state is only a re-render tick, so a
 * shape whose path changes reads the new path's HTML on the same render instead of showing the
 * old board for a frame.
 */
export function useCanvasFileHtml(path: string): string | undefined {
  const [, rerender] = useReducer((n: number) => n + 1, 0);
  useEffect(() => {
    if (canvasFileHtml.has(path)) return;
    let live = true;
    loadCanvasFileHtml(path).then(() => {
      if (live) rerender();
    });
    return () => {
      live = false;
    };
  }, [path]);
  return canvasFileHtml.get(path);
}

const LAYOUT_PATTERN = /canvases\/([^/]+)\/layout\.json$/;

/**
 * Window event fired once `layouts` holds an edit. The canvas lays itself out again on it
 * (App.tsx) and the inspector re-reads the board's status (InspectorPanel.tsx). Between them,
 * that is everything a layout.json change can move.
 */
export const LAYOUT_CHANGED = "sp:layout";

/**
 * The layouts. Starts as the generated module's own map and is replaced wholesale when that
 * module re-executes, so a layout.json edit repaints the canvas instead of reloading the page.
 * Callers read through readCanvasLayout rather than holding this, which is what lets it be
 * swapped underneath them.
 */
let layouts: Record<string, CanvasLayoutConfig> = rawLayouts;

if (import.meta.hot) {
  // The status endpoint sends the layout.json it has just written, rather than leaving the page
  // to hear about the write from the file watcher: the watcher answers a settled batch of writes
  // and would have the badge lag the click it answers. The watcher sends this same message for a
  // layout.json edited by hand, so a status set twice over lands twice, identically.
  import.meta.hot.on(
    "sp:board-status",
    ({ slug, layout }: { slug: string; layout: CanvasLayoutConfig }) => {
      const key = Object.keys(layouts).find((path) => LAYOUT_PATTERN.exec(path)?.[1] === slug);
      if (!key) return;
      layouts = { ...layouts, [key]: layout };
      window.dispatchEvent(new Event(LAYOUT_CHANGED));
    },
  );

  // And whenever virtual:canvases re-executes for any other reason, it hands its fresh layouts
  // over here, because this module keeps the bindings of the *old* copy of it and would otherwise
  // go on reading the layouts the page started with. That is Vite's own HMR update, which reaches
  // a layout.json only where the boards happen to sit inside the app's root; the message above is
  // what carries an edit in every other case.
  window.addEventListener("sp:canvases", (event) => {
    layouts = (event as CustomEvent<Record<string, CanvasLayoutConfig>>).detail;
    window.dispatchEvent(new Event(LAYOUT_CHANGED));
  });
}

/** This board's layout.json, if it dropped one next to its HTML files. */
export function readCanvasLayout(
  pageSlug: string,
): CanvasLayoutConfig | undefined {
  for (const [path, config] of Object.entries(layouts)) {
    if (LAYOUT_PATTERN.exec(path)?.[1] === pageSlug) return config;
  }
  return undefined;
}

/**
 * This folder's inlined images by payload key, if it committed the files they came from: the
 * inspector's Assets tab joins a board's data: URIs against it to put a file name next to each
 * one. Undefined for a folder with no `assets/`, `assets-dark/` or `assets.json`.
 */
export function readCanvasAssetNames(pageSlug: string) {
  return rawAssetNames[pageSlug];
}

const ICON_PATTERN = /canvases\/([^/]+)\/icon\.png$/;

/** This folder's app icon, if it dropped one next to its HTML files. */
export function canvasIconUrl(pageSlug: string) {
  for (const [path, url] of Object.entries(rawIcons)) {
    if (ICON_PATTERN.exec(path)?.[1] === pageSlug) return url;
  }
  return undefined;
}

/** Every discovered board, grouped by page and sorted by filename within it. */
export function readCanvasLibrary(): CanvasLibraryFile[][] {
  const byPage = new Map<string, CanvasLibraryFile[]>();
  for (const path of Object.keys(fileLoaders)) {
    const file = parse(path);
    if (!file) continue;
    const list = byPage.get(file.pageSlug) ?? [];
    list.push(file);
    byPage.set(file.pageSlug, list);
  }
  for (const list of byPage.values()) {
    list.sort((a, b) =>
      a.fileName.localeCompare(b.fileName, undefined, { numeric: true }),
    );
  }
  // numeric: true so 02- sorts before 10-, and v1.9 before v1.13. Then `order`: sort is
  // stable, so it only moves the folders that ask to be moved.
  const rank = (slug: string) =>
    slug === WELCOME_PAGE_SLUG ? -Infinity : (readCanvasLayout(slug)?.order ?? 0);
  return [...byPage.entries()]
    .sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
    .sort(([a], [b]) => rank(a) - rank(b))
    .map(([, files]) => files);
}
