/**
 * The board source, generated by the `prototyping-canvases` plugin in
 * vite.config.ts. It replaces three `import.meta.glob` calls that could only
 * ever read `../../mockups/canvases`, because a glob pattern is a string
 * literal resolved at build time and cannot be pointed at the directory of
 * whoever installed the plugin.
 *
 * The three shapes below are exactly what those globs produced, so everything
 * downstream in canvasLibrary.ts is unchanged — including the two eager maps
 * staying synchronous, which matters because they are read during render.
 *
 * Keys keep the historical `../../mockups/canvases/<slug>/<file>` spelling
 * whatever directory the boards really came from. They seed tldraw shape ids
 * (App.tsx), and the store persists, so changing the spelling would orphan
 * every shape in an existing document.
 */
declare module "virtual:canvases" {
  import type { CommentsFile } from "./canvasComments";
  import type { CanvasLayoutConfig } from "./canvasLibrary";

  /** Board HTML, one lazy chunk per file, fetched when a shape first shows it. */
  export const fileLoaders: Record<string, () => Promise<string>>;
  /** Each folder's layout.json, eager: read during render. */
  export const rawLayouts: Record<string, CanvasLayoutConfig>;
  /** Each folder's icon.png as an emitted asset URL, eager: read during render. */
  export const rawIcons: Record<string, string>;
  /**
   * Per folder slug, `"<payload length>:<fnv1a>"` of a data: URI's base64 payload -> the file
   * in that folder it was inlined from. Built from `assets/**`, `assets-dark/**` and
   * `assets.json`, so it needs no attribute in the HTML and no regeneration; eager because it
   * is small (about 60 bytes per asset) and read while a panel renders.
   */
  export const rawAssetNames: Record<string, Record<string, { name: string; bytes: number }>>;
  /**
   * Absolute path the boards were actually read from, and `""` in a production build — the
   * bundle is public and this is the build machine's filesystem. EmptyLibraryNotice in App.tsx
   * shows it to a project that has no boards yet, because "which directory is this canvas
   * showing" is the first question when a board is missing, and the answer is otherwise only in
   * the dev server's own environment.
   */
  export const canvasesDir: string;

  /**
   * Each folder's comments.json, keyed by slug — the canvas's own comments, which live with the
   * boards in Git rather than in a sync server. Inlined rather than imported, so writing one back
   * (canvasComments.ts posts to `/__sp/comments`) does not reload the page through the module
   * graph while its composer is still open. Missing for a folder nobody has commented on.
   */
  export const rawComments: Record<string, CommentsFile>;

  /**
   * Suffix that keeps two projects' documents apart, `":<hash>"` or `""`. Every canvas runs on
   * 127.0.0.1, so the origin cannot tell them apart and the persistence key has to. Empty for
   * this checkout's own boards, and in a build, so the repo and the hosted canvas keep the
   * document they already have. App.tsx appends it to PERSISTENCE_KEY.
   */
  export const canvasesNamespace: string;
}
