/**
 * The board source, generated by the `prototyping-canvases` plugin in
 * vite.config.ts. It replaces three `import.meta.glob` calls that could only
 * ever read `../../mockups/canvases`, because a glob pattern is a string
 * literal resolved at build time and cannot be pointed at the directory of
 * whoever installed the plugin.
 *
 * The three shapes below are exactly what those globs produced, so everything
 * downstream in canvasLibrary.ts is unchanged — including the two eager maps
 * staying synchronous, which matters because they are read during render.
 *
 * Keys keep the historical `../../mockups/canvases/<slug>/<file>` spelling
 * whatever directory the boards really came from. They seed tldraw shape ids
 * (App.tsx), and the store persists, so changing the spelling would orphan
 * every shape in an existing document.
 */
declare module "virtual:canvases" {
  import type { CanvasLayoutConfig } from "./canvasLibrary";

  /** Board HTML, one lazy chunk per file, fetched when a shape first shows it. */
  export const fileLoaders: Record<string, () => Promise<string>>;
  /** Each folder's layout.json, eager: read during render. */
  export const rawLayouts: Record<string, CanvasLayoutConfig>;
  /** Each folder's icon.png as an emitted asset URL, eager: read during render. */
  export const rawIcons: Record<string, string>;
  /** Absolute path the boards were read from, for the "no boards found" message. */
  export const canvasesDir: string;
}
